package scotch

var Scotches = []string{
	"The Glenlivet Nadurra Oloroso Single Malt",
	"Glenmorangie Quinta Ruban 12 Year Old Single Malt Scotch Port Cask Finish",
	"Ardmore Traditional Cask Highland Single Malt",
	"Clynelish 14 Year Old Single Malt",
	"Ancnoc 16 Year Old Single Malt",
	"Glen Garioch Vintage 1994",
	"Balvenie 12 Year Old Doublewood Single Malt",
	"Glengoyne 17 Year Old Single Malt",
	"Laphroaig Triple Wood Single Malt",
	"Aberfeldy 12 Year Old Single Malt",
	"Glenmorangie Quinta Ruban 12 Year Old Single Malt",
	"The Dalmore 15 Year Old Single Malt",
	"Aberlour A'bunadh Single Malt",
	"Aberlour 16 Year Old Single Malt",
	"Johnnie Walker Green Label",
	"Talisker 10 Year Old Single Malt",
	"The Dalmore 12 Year Old Single Malt",
	"Old Pulteney 17 Year Old Single Malt",
	"Glenlivet Nadurra 16 Year Old Cask Strength Single Malt",
	"Tomatin 18 Year Old Single Malt",
	"Ardbeg Corryvreckan Single Malt",
	"Laphroaig Quarter Cask Single Malt",
	"Johnnie Walker Gold Label",
	"Talisker 1992 Distillers Edition",
	"Balvenie 15 Year Old Single Barrel Single Malt",
	"Glenlivet 18 Year Old Single Malt",
	"Laphroaig 10 Year Old Single Malt Scotch",
	"Ardbeg Uigeadail",
	"Laphroaig 10 Year Old Cask Strength Islay Single Malt",
	"Lagavulin 16",
}
